<a href="https://colab.research.google.com/github/AP-CMET/Streamlit_tutorial/blob/main/Week5_Workshop_ML_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔒 TUTOR DEMO · Week 5 Workshop · Pandas on the **diabetes** teaching data
Use this notebook to **demonstrate each step live**. Students then repeat the same step on their own **hypertension** data (*Week5_Workshop_Pandas_Student*). Step and task numbers match, so you can say "now do Task 4.1 on your data". The DataFrame is called **`df`** here too, so students can copy what you type.

**How to use:** show the code, run it, point at the output, then let students do their version. *Say:* lines are suggested talking points. **No loops today**; they come next week.

### How the two datasets differ
| | Diabetes (your demo) | Hypertension (students) |
|---|---|---|
| Rows × columns | 8,045 × 19 | 5,000 × 18 |
| Target | `Diabetes_Risk` | `Hypertension` |
| Duplicates | **45** | **0** |
| Inconsistent categories | **Gender** (Female / female / F ...) | none |
| Missing values | 8 columns, Alcohol largest (35%) | 8 columns, Alcohol largest (27%) |
| Columns that measure the condition | Fasting glucose, HbA1c | Systolic/diastolic BP and `BP_Category` define the label exactly |

**Note:** "My data had duplicates and messy spellings. Yours may not. Checking and finding nothing is still a finding."

my username for github-st20317830@outlook.cardiffmet.ac.uk

In [3]:
username = "AP-CMET"
repo = "tutorial_github"
!git clone https://github.com/{username}/{repo}.git
%cd {repo}
%ls

Cloning into 'tutorial_github'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 266.06 KiB | 4.75 MiB/s, done.
Resolving deltas: 100% (2/2), done.
/content/tutorial_github
diabetes_risk_teaching_dataset_8000.csv  Workshop_1_Week_2_Solutions.ipynb

### **Import all the necessary libraries:**

In [1]:
import pandas as pd

Clone cell (skip if you load the file directly):

## Step 1 · Load and understand the data  *(2a)*
**Say:** "First: how big is it, what are the columns, what types?"

In [5]:
df = pd.read_csv('diabetes_risk_teaching_dataset_8000.csv')
df

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
0,32.5,Female,28.4,NaN,Average,Sedentary,Occasional,Never,7.5,5.4,High,Yes,174.8,137,69.4,101.4,4.16,Normal,No
1,43.9,Female,30.6,79.6,Average,Sedentary,Heavy,Former,5.8,5.2,Low,Yes,225.0,121,122.0,114.9,4.72,Normal,Yes
2,57.1,Male,22.2,59.4,Poor,Light,NaN,Never,NaN,6.0,Very High,No,240.1,130,74.4,77.5,4.14,Normal,No
3,65.6,Female,25.1,75.2,Poor,Moderate,Occasional,Current,7.6,6.3,Moderate,No,213.0,108,65.8,82.8,4.26,Normal,No
4,48.5,Female,31.7,81.2,Average,Light,Moderate,Never,8.8,6.3,Moderate,Yes,240.8,154,54.0,100.0,4.03,Normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,35.0,male,31.8,85.7,Average,Active,NaN,Current,5.5,2.9,Moderate,No,158.9,119,140.7,99.9,4.08,Normal,No
8041,50.9,Female,32.4,96.8,Excellent,Moderate,Occasional,Current,6.4,3.5,Low,Yes,196.9,131,74.8,97.4,4.22,Normal,No
8042,50.9,M,17.4,55.0,NaN,Active,Occasional,Never,6.7,7.7,Moderate,No,NaN,112,80.6,65.0,3.80,Normal,No
8043,36.2,Male,33.2,92.4,Average,Light,Moderate,Never,4.7,2.0,Low,No,243.5,156,68.5,104.2,4.91,Normal,Yes
8044,53.4,Female,24.6,67.8,Good,Sedentary,NaN,Never,7.4,5.6,Moderate,Yes,217.4,133,135.7,89.3,4.39,Normal,No

**1.2** First 5 rows

In [ ]:
df.head()

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
0,32.5,Female,28.4,NaN,Average,Sedentary,Occasional,Never,7.5,5.4,High,Yes,174.8,137,69.4,101.4,4.16,Normal,No
1,43.9,Female,30.6,79.6,Average,Sedentary,Heavy,Former,5.8,5.2,Low,Yes,225.0,121,122.0,114.9,4.72,Normal,Yes
2,57.1,Male,22.2,59.4,Poor,Light,NaN,Never,NaN,6.0,Very High,No,240.1,130,74.4,77.5,4.14,Normal,No
3,65.6,Female,25.1,75.2,Poor,Moderate,Occasional,Current,7.6,6.3,Moderate,No,213.0,108,65.8,82.8,4.26,Normal,No
4,48.5,Female,31.7,81.2,Average,Light,Moderate,Never,8.8,6.3,Moderate,Yes,240.8,154,54.0,100.0,4.03,Normal,No

**1.3** Last 3 rows

In [ ]:
df.tail()

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
8040,35.0,male,31.8,85.7,Average,Active,NaN,Current,5.5,2.9,Moderate,No,158.9,119,140.7,99.9,4.08,Normal,No
8041,50.9,Female,32.4,96.8,Excellent,Moderate,Occasional,Current,6.4,3.5,Low,Yes,196.9,131,74.8,97.4,4.22,Normal,No
8042,50.9,M,17.4,55.0,NaN,Active,Occasional,Never,6.7,7.7,Moderate,No,NaN,112,80.6,65.0,3.80,Normal,No
8043,36.2,Male,33.2,92.4,Average,Light,Moderate,Never,4.7,2.0,Low,No,243.5,156,68.5,104.2,4.91,Normal,Yes
8044,53.4,Female,24.6,67.8,Good,Sedentary,NaN,Never,7.4,5.6,Moderate,Yes,217.4,133,135.7,89.3,4.39,Normal,No

In [ ]:
df

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
0,32.5,Female,28.4,NaN,Average,Sedentary,Occasional,Never,7.5,5.4,High,Yes,174.8,137,69.4,101.4,4.16,Normal,No
1,43.9,Female,30.6,79.6,Average,Sedentary,Heavy,Former,5.8,5.2,Low,Yes,225.0,121,122.0,114.9,4.72,Normal,Yes
2,57.1,Male,22.2,59.4,Poor,Light,NaN,Never,NaN,6.0,Very High,No,240.1,130,74.4,77.5,4.14,Normal,No
3,65.6,Female,25.1,75.2,Poor,Moderate,Occasional,Current,7.6,6.3,Moderate,No,213.0,108,65.8,82.8,4.26,Normal,No
4,48.5,Female,31.7,81.2,Average,Light,Moderate,Never,8.8,6.3,Moderate,Yes,240.8,154,54.0,100.0,4.03,Normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,35.0,male,31.8,85.7,Average,Active,NaN,Current,5.5,2.9,Moderate,No,158.9,119,140.7,99.9,4.08,Normal,No
8041,50.9,Female,32.4,96.8,Excellent,Moderate,Occasional,Current,6.4,3.5,Low,Yes,196.9,131,74.8,97.4,4.22,Normal,No
8042,50.9,M,17.4,55.0,NaN,Active,Occasional,Never,6.7,7.7,Moderate,No,NaN,112,80.6,65.0,3.80,Normal,No
8043,36.2,Male,33.2,92.4,Average,Light,Moderate,Never,4.7,2.0,Low,No,243.5,156,68.5,104.2,4.91,Normal,Yes
8044,53.4,Female,24.6,67.8,Good,Sedentary,NaN,Never,7.4,5.6,Moderate,Yes,217.4,133,135.7,89.3,4.39,Normal,No

**1.4** Rows and columns

In [6]:
df.shape

(8045, 19)

**1.5** `info()`

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8045 entries, 0 to 8044
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           8045 non-null   float64
 1   Gender                        8045 non-null   object
 2   BMI                           8045 non-null   float64
 3   Waist_Circumference_cm        7868 non-null   float64
 4   Diet_Quality                  7901 non-null   object
 5   Physical_Activity             8045 non-null   object
 6   Alcohol_Consumption           5262 non-null   object
 7   Smoking_Status                8045 non-null   object
 8   Sleep_Hours                   7844 non-null   float64
 9   Screen_Time_Hours             7923 non-null   float64
 10  Stress_Level                  7949 non-null   object
 11  Family_History_Diabetes       8045 non-null   object
 12  Cholesterol_mg_dL             7787 non-null   float64
 13  Blood_Pressure_Systolic_mmHg  8045 non-null   int64
 14  Insulin_Level                 7717 non-null   float64
 15  Fasting_Glucose_mg_dL         8045 non-null   float64
 16  HbA1c_percent                 8045 non-null   float64
 17  Risk_Category                 8045 non-null   object
 18  Diabetes_Risk                 8045 non-null   object
dtypes: float64(9), int64(1), object(9)
memory usage: 1.2+ MB

**1.6** `describe()`

In [ ]:
df.describe()

,Age,BMI,Waist_Circumference_cm,Sleep_Hours,Screen_Time_Hours,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent
count,8045.000000,8045.000000,7868.000000,7844.000000,7923.000000,7787.000000,8045.000000,7717.000000,8045.000000,8045.000000
mean,46.020087,27.124674,74.159291,6.787111,5.492818,197.592102,123.409198,84.336931,90.239925,4.216838
std,14.572359,5.475407,14.323700,1.295650,2.216880,35.537930,15.123776,31.277729,12.731273,0.402509
min,18.000000,15.000000,55.000000,3.000000,0.000000,110.000000,90.000000,15.000000,65.000000,3.800000
25%,35.800000,23.300000,62.300000,5.900000,4.000000,173.000000,113.000000,62.900000,81.400000,3.800000
50%,45.800000,27.100000,73.200000,6.800000,5.500000,197.300000,123.000000,84.500000,90.100000,4.140000
75%,55.700000,30.800000,83.800000,7.700000,7.000000,221.550000,134.000000,105.000000,98.900000,4.490000
max,90.000000,47.300000,135.200000,11.000000,13.700000,335.000000,180.000000,188.800000,137.900000,5.970000

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,8045.0,46.020087,14.572359,18.0,35.8,45.80,55.70,90.00
BMI,8045.0,27.124674,5.475407,15.0,23.3,27.10,30.80,47.30
Waist_Circumference_cm,7868.0,74.159291,14.323700,55.0,62.3,73.20,83.80,135.20
Sleep_Hours,7844.0,6.787111,1.295650,3.0,5.9,6.80,7.70,11.00
Screen_Time_Hours,7923.0,5.492818,2.216880,0.0,4.0,5.50,7.00,13.70
Cholesterol_mg_dL,7787.0,197.592102,35.537930,110.0,173.0,197.30,221.55,335.00
Blood_Pressure_Systolic_mmHg,8045.0,123.409198,15.123776,90.0,113.0,123.00,134.00,180.00
Insulin_Level,7717.0,84.336931,31.277729,15.0,62.9,84.50,105.00,188.80
Fasting_Glucose_mg_dL,8045.0,90.239925,12.731273,65.0,81.4,90.10,98.90,137.90
HbA1c_percent,8045.0,4.216838,0.402509,3.8,3.8,4.14,4.49,5.97

**1.7** Types: **Say:** "Numbers get maths; text gets counts."

In [ ]:
df.dtypes.value_counts()

float64    9
object     9
int64      1
Name: count, dtype: int64

**1.8** Mini data dictionary

In [ ]:
pd.DataFrame({'dtype': df.dtypes.astype(str),
              'unique': df.nunique(),
              'missing': df.isnull().sum()})

                                dtype  unique  missing
Age                           float64     666        0
Gender                         object       6        0
BMI                           float64     291        0
Waist_Circumference_cm        float64     610      177
Diet_Quality                   object       4      144
Physical_Activity              object       4        0
Alcohol_Consumption            object       3     2783
Smoking_Status                 object       3        0
Sleep_Hours                   float64      81      201
Screen_Time_Hours             float64     129      122
Stress_Level                   object       4       96
Family_History_Diabetes        object       2        0
Cholesterol_mg_dL             float64    1593      258
Blood_Pressure_Systolic_mmHg    int64      87        0
Insulin_Level                 float64    1377      328
Fasting_Glucose_mg_dL         float64     607        0
HbA1c_percent                 float64     191        0
Risk_Category                  object       2        0
Diabetes_Risk                  object       2        0

## Step 2 · Select, filter and sort  *(2a)*
**Say:** "A condition gives True/False for every row; put it inside the brackets to keep the True rows. Each condition goes in its own brackets."

**2.1** Select columns

In [8]:
df[['Age', 'BMI', 'Diabetes_Risk']]

       Age   BMI Diabetes_Risk
0     32.5  28.4            No
1     43.9  30.6           Yes
2     57.1  22.2            No
3     65.6  25.1            No
4     48.5  31.7            No
...    ...   ...           ...
8040  35.0  31.8            No
8041  50.9  32.4            No
8042  50.9  17.4            No
8043  36.2  33.2           Yes
8044  53.4  24.6            No

[8045 rows x 3 columns]

**2.2** `iloc`

In [ ]:
df.iloc[0]

Age                                   32.5
Gender                              Female
BMI                                   28.4
Waist_Circumference_cm                 NaN
Diet_Quality                       Average
Physical_Activity                Sedentary
Alcohol_Consumption             Occasional
Smoking_Status                       Never
Sleep_Hours                            7.5
Screen_Time_Hours                      5.4
Stress_Level                          High
Family_History_Diabetes                Yes
Cholesterol_mg_dL                    174.8
Blood_Pressure_Systolic_mmHg           137
Insulin_Level                         69.4
Fasting_Glucose_mg_dL                101.4
HbA1c_percent                         4.16
Risk_Category                       Normal
Diabetes_Risk                           No
Name: 0, dtype: object

**2.3** Over 60

In [12]:
[df['Age'] > 60]

[0       False
 1       False
 2       False
 3        True
 4       False
         ...
 8040    False
 8041    False
 8042    False
 8043    False
 8044    False
 Name: Age, Length: 8045, dtype: bool]

In [18]:
df[df['Age'] > 60]

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
3,65.6,Female,25.1,75.2,Poor,Moderate,Occasional,Current,7.6,6.3,Moderate,No,213.0,108,65.8,82.8,4.26,Normal,No
13,65.1,F,26.2,63.7,Average,Light,NaN,Former,8.8,7.8,Moderate,No,184.7,139,90.1,79.5,3.80,Normal,No
19,69.4,Male,18.9,55.0,Poor,Moderate,Moderate,Former,6.3,1.1,Low,No,232.9,145,78.4,73.0,3.80,Normal,No
22,70.1,F,15.0,55.0,Average,Active,Occasional,Never,3.6,5.2,Very High,Yes,139.1,103,15.0,65.0,3.80,Normal,No
31,63.2,Male,26.3,78.8,Average,Moderate,Occasional,Former,7.3,4.3,Low,Yes,228.8,104,77.2,78.4,4.17,Normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8013,67.4,Female,21.9,60.0,Average,Sedentary,NaN,Current,5.2,3.6,Moderate,No,151.3,125,75.7,95.7,4.95,Normal,No
8018,64.1,female,41.6,121.1,Good,Sedentary,Occasional,Former,4.7,10.6,Very High,No,210.5,116,141.8,118.4,4.59,Normal,Yes
8020,71.9,Female,18.9,55.0,Poor,Moderate,NaN,Former,5.9,1.6,Moderate,Yes,191.4,129,59.9,73.4,3.80,Normal,No
8021,72.4,Female,24.1,66.2,Good,Moderate,Heavy,Never,5.2,4.3,Moderate,Yes,219.4,126,81.3,85.6,4.05,Normal,No
8039,76.9,Male,18.9,55.0,NaN,Light,Occasional,Current,7.2,6.0,Moderate,No,165.0,97,92.5,98.5,4.75,Normal,Yes

In [19]:
len(df[df['Age'] > 60])

1367

**2.4** `and`: over 60 and current smoker

In [21]:
len(df[(df['Age'] > 60) & (df['Smoking_Status'] == 'Current')])

269

**2.5** `or`: BMI over 35 or over age 70

In [22]:
(df[(df['BMI'] > 35) | (df['Age'] > 70)])

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
22,70.1,F,15.0,55.0,Average,Active,Occasional,Never,3.6,5.2,Very High,Yes,139.1,103,15.0,65.0,3.80,Normal,No
26,43.2,Male,40.2,94.0,Average,Sedentary,Moderate,Never,6.5,6.4,Moderate,No,229.4,115,88.4,120.0,4.34,Normal,Yes
27,41.3,Female,36.8,104.4,Poor,Sedentary,NaN,Former,7.4,6.5,High,No,161.1,99,111.8,102.8,4.38,Normal,No
28,43.2,Female,36.2,106.7,Average,Moderate,NaN,Never,7.2,2.7,Low,No,234.8,137,132.1,99.4,4.76,Normal,Yes
35,43.9,female,38.9,109.1,Average,Sedentary,NaN,Current,7.1,2.5,Moderate,No,194.9,134,125.4,120.7,5.18,Normal,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8020,71.9,Female,18.9,55.0,Poor,Moderate,NaN,Former,5.9,1.6,Moderate,Yes,191.4,129,59.9,73.4,3.80,Normal,No
8021,72.4,Female,24.1,66.2,Good,Moderate,Heavy,Never,5.2,4.3,Moderate,Yes,219.4,126,81.3,85.6,4.05,Normal,No
8037,56.7,Female,36.7,97.8,Poor,Light,NaN,Former,3.8,7.0,Moderate,Yes,198.6,156,NaN,111.9,4.95,Normal,Yes
8038,59.3,Female,38.9,93.2,Average,Sedentary,Occasional,Current,7.1,8.9,Moderate,No,NaN,133,97.0,114.9,4.69,Normal,Yes
8039,76.9,Male,18.9,55.0,NaN,Light,Occasional,Current,7.2,6.0,Moderate,No,165.0,97,92.5,98.5,4.75,Normal,Yes

**2.6** `isin`

In [25]:
(df[df['Physical_Activity'].isin(['Active', 'Moderate'])])

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
3,65.6,Female,25.1,75.2,Poor,Moderate,Occasional,Current,7.6,6.3,Moderate,No,213.0,108,65.8,82.8,4.26,Normal,No
7,47.0,female,22.7,60.1,Average,Moderate,Heavy,Never,5.9,9.4,Low,No,260.5,132,103.5,87.3,3.83,Normal,No
10,50.1,Male,32.2,84.4,Good,Moderate,Moderate,Never,5.0,9.2,Low,No,275.9,113,122.4,102.7,4.38,Normal,No
16,54.7,female,18.1,55.0,Average,Moderate,NaN,Former,6.6,6.2,Low,No,192.7,114,15.0,83.3,4.26,Normal,No
17,51.4,Female,27.1,85.7,Average,Active,Occasional,Never,6.6,8.1,Moderate,No,208.7,105,71.0,74.3,3.80,Normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8031,42.1,Female,33.3,90.0,Good,Active,NaN,Never,5.2,3.0,Low,Yes,127.9,104,87.7,91.1,4.37,Normal,No
8035,41.9,Male,25.7,72.5,Average,Moderate,Occasional,Never,5.4,7.0,Moderate,No,161.7,90,93.4,92.7,4.02,Normal,No
8040,35.0,male,31.8,85.7,Average,Active,NaN,Current,5.5,2.9,Moderate,No,158.9,119,140.7,99.9,4.08,Normal,No
8041,50.9,Female,32.4,96.8,Excellent,Moderate,Occasional,Current,6.4,3.5,Low,Yes,196.9,131,74.8,97.4,4.22,Normal,No
8042,50.9,M,17.4,55.0,NaN,Active,Occasional,Never,6.7,7.7,Moderate,No,NaN,112,80.6,65.0,3.80,Normal,No

In [24]:
len(df[df['Physical_Activity'].isin(['Active', 'Moderate'])])

3216

**2.7** Sort: highest BMI

In [ ]:
df.sort_values('BMI', ascending=False)

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
2600,61.1,F,47.3,135.2,Average,Light,Occasional,Never,8.2,5.6,Low,No,191.2,120,140.4,120.3,5.00,Normal,Yes
1623,71.0,Female,45.4,116.1,Average,Sedentary,Moderate,Never,7.1,5.8,Low,No,182.9,159,98.2,123.8,4.73,Normal,Yes
977,40.3,Female,45.3,116.6,Average,Active,Moderate,Former,7.0,2.7,Low,No,306.8,134,61.5,119.6,5.41,Normal,Yes
4945,25.1,Male,45.2,125.8,Poor,Sedentary,Moderate,Former,5.1,2.2,Very High,No,190.7,173,53.8,112.6,4.88,Normal,Yes
1011,56.7,M,44.7,121.1,Average,Sedentary,NaN,Former,7.7,NaN,Low,No,228.2,161,123.7,137.9,5.81,Prediabetes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,31.0,Male,15.0,55.0,Good,Moderate,NaN,Never,9.6,8.0,Moderate,No,235.7,108,117.1,65.0,3.80,Normal,No
3624,18.0,F,15.0,55.0,Average,Light,Occasional,Former,7.6,6.3,Very High,No,158.3,117,52.4,73.1,3.80,Normal,No
226,49.0,Female,15.0,55.0,Average,Light,Occasional,Current,NaN,4.6,Moderate,No,134.1,109,22.7,75.4,3.80,Normal,No
6250,47.3,Male,15.0,55.0,NaN,Light,Moderate,Never,9.2,2.9,Moderate,No,208.9,92,96.5,71.6,3.92,Normal,No
22,70.1,F,15.0,55.0,Average,Active,Occasional,Never,3.6,5.2,Very High,Yes,139.1,103,15.0,65.0,3.80,Normal,No

**2.8** Sort by two columns

In [ ]:
df.sort_values(['Physical_Activity', 'Age'], ascending=[True, False])

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk
1089,90.0,Male,31.6,84.8,Average,Active,Occasional,Never,5.1,6.4,High,Yes,190.9,97,94.3,102.8,4.50,Normal,Yes
3296,90.0,Male,25.4,66.7,Average,Active,NaN,Never,6.9,3.9,Moderate,Yes,208.3,112,112.6,89.4,4.08,Normal,No
5145,90.0,Female,21.3,55.0,Good,Active,NaN,Never,7.4,8.0,Moderate,No,195.3,123,45.2,84.9,4.28,Normal,No
966,89.6,male,24.0,58.2,Average,Active,Occasional,Never,8.0,6.4,Low,No,121.6,98,56.1,91.2,4.30,Normal,No
6598,88.0,Female,26.9,66.9,Poor,Active,NaN,Never,6.6,4.7,Moderate,No,196.1,132,89.6,79.7,3.80,Normal,No

## Step 3 · Summary statistics  *(2a)*

**3.1** Mean age

In [26]:
df['Age'].mean().round(2)

np.float64(46.02)

**3.2** Count each smoking status

In [ ]:
df['Smoking_Status'].value_counts()

Smoking_Status
Never      4403
Former     2065
Current    1577
Name: count, dtype: int64

**3.3** `nunique`

In [29]:
df['Physical_Activity'].value_counts()

Physical_Activity
Sedentary    2444
Light        2385
Moderate     2020
Active       1196
Name: count, dtype: int64

In [27]:
df['Physical_Activity'].nunique()

4

**3.4** `agg` in one table

In [30]:
df[['Blood_Pressure_Systolic_mmHg', 'BMI']].agg(['median', 'min', 'max'])

        Blood_Pressure_Systolic_mmHg   BMI
median                         123.0  27.1
min                             90.0  15.0
max                            180.0  47.3

### ✅ Checkpoint 1: commit, e.g. *"Loaded data and explored structure"*

## Step 4 · Duplicates and categories  *(2a / 2b)*
**Say:** "Do not assume the data is clean. Check."

**4.1** Duplicates

In [ ]:
df.duplicated().sum()

np.int64(45)

In [ ]:
df = df.drop_duplicates()
len(df)

8000

**4.2** Gender categories. **Say:** "Female, female and F are the same thing."

In [ ]:
df['Gender'].value_counts()

Gender
Female    3300
Male      3065
male       423
F          416
female     409
M          387
Name: count, dtype: int64

Fix with `replace`:

In [ ]:
df['Gender'] = df['Gender'].replace({'F': 'Female', 'female': 'Female', 'M': 'Male', 'male': 'Male'})
df['Gender'].value_counts()

Gender
Female    4148
Male      3897
Name: count, dtype: int64

**4.3** Smoking status

In [ ]:
df['Smoking_Status'].value_counts()

Smoking_Status
Never      4381
Former     2049
Current    1570
Name: count, dtype: int64

**4.4** Physical activity

In [ ]:
df['Physical_Activity'].value_counts()

Physical_Activity
Sedentary    2436
Light        2374
Moderate     2001
Active       1189
Name: count, dtype: int64

**Extension: range check**

In [ ]:
q1 = df['BMI'].quantile(0.25)
q3 = df['BMI'].quantile(0.75)
iqr = q3 - q1
((df['BMI'] < q1 - 1.5 * iqr) | (df['BMI'] > q3 + 1.5 * iqr)).sum()

np.int64(32)

## Step 5 · Missing values  *(2a / 2b)*
**Say:** "Different columns need different treatment. Number column: median. Text column: most common value. Alcohol blanks are people with no alcohol recorded, so I use a label."

**5.1** Count gaps

In [ ]:
missing_count = df.isnull().sum()
missing_count

Age                                0
Gender                             0
BMI                                0
Waist_Circumference_cm           176
Diet_Quality                     144
Physical_Activity                  0
Alcohol_Consumption             2765
Smoking_Status                     0
Sleep_Hours                      200
Screen_Time_Hours                120
Stress_Level                      96
Family_History_Diabetes            0
Cholesterol_mg_dL                256
Blood_Pressure_Systolic_mmHg       0
Insulin_Level                    328
Fasting_Glucose_mg_dL              0
HbA1c_percent                      0
Risk_Category                      0
Diabetes_Risk                      0
dtype: int64

**5.2** Percentage, largest first

In [ ]:

missing_count = df.isnull().sum()
missing_percent = (df.isnull().mean() * 100).round(1)

missing_df = pd.DataFrame({
    'Missing Values': missing_count,
    'Missing Percentage (%)': missing_percent
})

missing_df = missing_df[missing_df['Missing Values'] > 0] #removes the column where there is no missing values

missing_df

                        Missing Values  Missing Percentage (%)
Waist_Circumference_cm             177                     2.2
Diet_Quality                       144                     1.8
Alcohol_Consumption               2783                    34.6
Sleep_Hours                        201                     2.5
Screen_Time_Hours                  122                     1.5
Stress_Level                        96                     1.2
Cholesterol_mg_dL                  258                     3.2
Insulin_Level                      328                     4.1

**5.3** Median for number columns

In [ ]:
df.loc[:, 'Waist_Circumference_cm'] = df['Waist_Circumference_cm'].fillna(
    df['Waist_Circumference_cm'].median()
)

df.loc[:, 'Sleep_Hours'] = df['Sleep_Hours'].fillna(
    df['Sleep_Hours'].median()
)

df.loc[:, 'Screen_Time_Hours'] = df['Screen_Time_Hours'].fillna(
    df['Screen_Time_Hours'].median()
)

df.loc[:, 'Cholesterol_mg_dL'] = df['Cholesterol_mg_dL'].fillna(
    df['Cholesterol_mg_dL'].median()
)

df.loc[:, 'Insulin_Level'] = df['Insulin_Level'].fillna(
    df['Insulin_Level'].median()
)

**5.4** Mode for text columns

In [ ]:
df.loc[:, 'Diet_Quality'] = df['Diet_Quality'].fillna(
    df['Diet_Quality'].mode()[0]
)

df.loc[:, 'Stress_Level'] = df['Stress_Level'].fillna(
    df['Stress_Level'].mode()[0]
)

**5.5** A label for Alcohol

In [ ]:
df.loc[:, 'Alcohol_Consumption'] = df['Alcohol_Consumption'].fillna('None')

**5.6** Check

In [ ]:
count=df.isnull().sum()
count

Age                             0
Gender                          0
BMI                             0
Waist_Circumference_cm          0
Diet_Quality                    0
Physical_Activity               0
Alcohol_Consumption             0
Smoking_Status                  0
Sleep_Hours                     0
Screen_Time_Hours               0
Stress_Level                    0
Family_History_Diabetes         0
Cholesterol_mg_dL               0
Blood_Pressure_Systolic_mmHg    0
Insulin_Level                   0
Fasting_Glucose_mg_dL           0
HbA1c_percent                   0
Risk_Category                   0
Diabetes_Risk                   0
dtype: int64

### ✅ Checkpoint 2: commit, e.g. *"Checked duplicates and categories; handled missing values"*

## Step 6 · New columns with functions and conditions  *(2b)*
**Say:** "A function with if / elif / else turns a number into a group. `apply` runs it on every value; `apply(axis=1)` on every row."

**6.1** `bmi_group`

In [ ]:
def bmi_group(bmi):
    if bmi < 18.5:
        return 'Underweight'
    elif bmi < 25:
        return 'Normal'
    elif bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'

**6.2** Apply it

In [ ]:
df.loc[:, 'BMI_group'] = df['BMI'].apply(bmi_group) #applies your bmi_group function to every value in the BMI column

df['BMI_group'].value_counts() #counts how many records belong to each BMI category

BMI_group
Overweight     2832
Obese          2400
Normal         2334
Underweight     479
Name: count, dtype: int64

In [ ]:
df

,Age,Gender,BMI,Waist_Circumference_cm,Diet_Quality,Physical_Activity,Alcohol_Consumption,Smoking_Status,Sleep_Hours,Screen_Time_Hours,Stress_Level,Family_History_Diabetes,Cholesterol_mg_dL,Blood_Pressure_Systolic_mmHg,Insulin_Level,Fasting_Glucose_mg_dL,HbA1c_percent,Risk_Category,Diabetes_Risk,BMI_group
0,32.5,Female,28.4,NaN,Average,Sedentary,Occasional,Never,7.5,5.4,High,Yes,174.8,137,69.4,101.4,4.16,Normal,No,Overweight
1,43.9,Female,30.6,79.6,Average,Sedentary,Heavy,Former,5.8,5.2,Low,Yes,225.0,121,122.0,114.9,4.72,Normal,Yes,Obese
2,57.1,Male,22.2,59.4,Poor,Light,NaN,Never,NaN,6.0,Very High,No,240.1,130,74.4,77.5,4.14,Normal,No,Normal
3,65.6,Female,25.1,75.2,Poor,Moderate,Occasional,Current,7.6,6.3,Moderate,No,213.0,108,65.8,82.8,4.26,Normal,No,Overweight
4,48.5,Female,31.7,81.2,Average,Light,Moderate,Never,8.8,6.3,Moderate,Yes,240.8,154,54.0,100.0,4.03,Normal,No,Obese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8040,35.0,Male,31.8,85.7,Average,Active,NaN,Current,5.5,2.9,Moderate,No,158.9,119,140.7,99.9,4.08,Normal,No,Obese
8041,50.9,Female,32.4,96.8,Excellent,Moderate,Occasional,Current,6.4,3.5,Low,Yes,196.9,131,74.8,97.4,4.22,Normal,No,Obese
8042,50.9,Male,17.4,55.0,NaN,Active,Occasional,Never,6.7,7.7,Moderate,No,NaN,112,80.6,65.0,3.80,Normal,No,Underweight
8043,36.2,Male,33.2,92.4,Average,Light,Moderate,Never,4.7,2.0,Low,No,243.5,156,68.5,104.2,4.91,Normal,Yes,Obese
8044,53.4,Female,24.6,67.8,Good,Sedentary,NaN,Never,7.4,5.6,Moderate,Yes,217.4,133,135.7,89.3,4.39,Normal,No,Normal

**6.3** `age_band`

In [ ]:
def age_band(age):
    if age < 30:
        return 'Under 30'
    elif age < 45:
        return '30-44'
    elif age < 60:
        return '45-59'
    else:
        return '60+'

**6.4** Apply it

In [ ]:
df.loc[:, 'Age_band'] = df['Age'].apply(age_band)

df['Age_band'].value_counts()

Age_band
45-59       2854
30-44       2651
60+         1378
Under 30    1162
Name: count, dtype: int64

**6.5** A rule across two columns (you can do this check with your bp columns)

In [ ]:
def glucose_status(row):
    if row['Fasting_Glucose_mg_dL'] >= 100 or row['HbA1c_percent'] >= 5.7:
        return 'Raised'
    else:
        return 'Normal'

**6.6** Apply row by row and compare with the label

In [ ]:
df.loc[:, 'Glucose_status'] = df.apply(glucose_status, axis=1)

pd.crosstab(df['Glucose_status'], df['Diabetes_Risk'])

Diabetes_Risk     No   Yes
Glucose_status
Normal          5605   647
Raised           637  1156

**6.7** Yes/No features

In [ ]:
df['Older'] = df['Age'] >= 60
df['Obese'] = df['BMI'] >= 30
df['High_glucose'] = df['Fasting_Glucose_mg_dL'] >= 100

/tmp/ipykernel_4356/2559343443.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Older'] = df['Age'] >= 60
/tmp/ipykernel_4356/2559343443.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Obese'] = df['BMI'] >= 30
/tmp/ipykernel_4356/2559343443.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['High_glucose'] = df['Fasting_Glucose_mg_dL'] >= 100

In [ ]:
df[['Age', 'Older', 'BMI', 'Obese',
    'Fasting_Glucose_mg_dL', 'High_glucose']].head()

    Age  Older   BMI  Obese  Fasting_Glucose_mg_dL  High_glucose
0  32.5  False  28.4  False                  101.4          True
1  43.9  False  30.6   True                  114.9          True
2  57.1  False  22.2  False                   77.5         False
3  65.6   True  25.1  False                   82.8         False
4  48.5  False  31.7   True                  100.0          True

**6.8** Count them

In [ ]:
df['Older'].value_counts()

Older
False    6628
True     1372
Name: count, dtype: int64

In [ ]:
df[['Older', 'Obese', 'High_glucose']].sum()

Older           1372
Obese           2390
High_glucose    1783
dtype: int64

**6.9** A derived column (students make `Pulse_pressure`)

In [ ]:
df['Waist_per_BMI'] = (df['Waist_Circumference_cm'] / df['BMI']).round(2)
df['Waist_per_BMI'].describe()

/tmp/ipykernel_4356/920465784.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Waist_per_BMI'] = (df['Waist_Circumference_cm'] / df['BMI']).round(2)

count    8000.000000
mean        2.756616
std         0.278223
min         1.760000
25%         2.580000
50%         2.730000
75%         2.890000
max         4.880000
Name: Waist_per_BMI, dtype: float64

**Extension:** lifestyle count (descriptive, not a prediction)

In [ ]:
def lifestyle_risk_count(row):

    count = 0

    if row['Physical_Activity'] == 'Sedentary':
        count += 1
    if row['Diet_Quality'] == 'Poor':
        count += 1
    if row['Alcohol_Consumption'] == 'Heavy':
        count += 1
    if row['Smoking_Status'] == 'Current':
        count += 1
    if row['Stress_Level'] in ['High', 'Very High']:
        count += 1
    return count

In [ ]:
df['Lifestyle_risk_count'] = df.apply(lifestyle_risk_count, axis=1)
df['Lifestyle_risk_count'].value_counts().sort_index()

/tmp/ipykernel_4356/1848402605.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Lifestyle_risk_count'] = df.apply(lifestyle_risk_count, axis=1)

Lifestyle_risk_count
0    2080
1    3325
2    2017
3     512
4      62
5       4
Name: count, dtype: int64

### Lifestyle Risk Count

The `Lifestyle_risk_count` feature is created by checking five lifestyle-related risk factors for each person.

| Lifestyle Factor | Risk Condition | Score |
|---|---|---:|
| Physical Activity | Sedentary | 1 |
| Diet Quality | Poor | 1 |
| Alcohol Consumption | Heavy | 1 |
| Smoking Status | Current | 1 |
| Stress Level | High or Very High | 1 |

Each risk factor contributes **1 point if present** and **0 points if absent**.

The points are added together to create a total `Lifestyle_risk_count` between **0 and 5**.

For example, if a person is sedentary, has a poor diet, currently smokes, and has high stress, their lifestyle risk count will be **4**.

**Why do this?**

* Because instead of looking at five separate lifestyle columns every time, you create one summary variable that says:
“How many of these selected lifestyle risks does this person have?”

## Step 7 · Encoding  *(2b)*
**Say:** "Averages and charts need numbers. I keep the text column and add a numeric copy next to it."

**7.1** `Diet_Quality_code`

In [ ]:
df['Diet_Quality_code'] = df['Diet_Quality'].map({'Poor': 0, 'Average': 1, 'Good': 2, 'Excellent': 3})

/tmp/ipykernel_4356/3019152543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Diet_Quality_code'] = df['Diet_Quality'].map({'Poor': 0, 'Average': 1, 'Good': 2, 'Excellent': 3})

**7.2** `Stress_Level_code`

In [ ]:
df['Stress_Level_code'] = df['Stress_Level'].map({'Low': 0, 'Moderate': 1, 'High': 2, 'Very High': 3})

/tmp/ipykernel_4356/3324128582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Stress_Level_code'] = df['Stress_Level'].map({'Low': 0, 'Moderate': 1, 'High': 2, 'Very High': 3})

**7.3** `Physical_Activity_code`

In [ ]:
df['Physical_Activity_code'] = df['Physical_Activity'].map({'Sedentary': 0, 'Light': 1, 'Moderate': 2, 'Active': 3})

/tmp/ipykernel_4356/3424733346.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Physical_Activity_code'] = df['Physical_Activity'].map({'Sedentary': 0, 'Light': 1, 'Moderate': 2, 'Active': 3})

**7.4** Check the mapping

In [ ]:
df[['Diet_Quality', 'Diet_Quality_code']].drop_duplicates()

   Diet_Quality  Diet_Quality_code
0       Average                  1
2          Poor                  0
6          Good                  2
15    Excellent                  3

**7.5** 1/0 flags

In [ ]:
df['Risk_flag'] = (df['Diabetes_Risk'] == 'Yes').astype(int)
df['Family_History_flag'] = (df['Family_History_Diabetes'] == 'Yes').astype(int)

/tmp/ipykernel_4356/224564264.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Risk_flag'] = (df['Diabetes_Risk'] == 'Yes').astype(int)
/tmp/ipykernel_4356/224564264.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Family_History_flag'] = (df['Family_History_Diabetes'] == 'Yes').astype(int)

**7.6** Overall proportion. **Say:** "The mean of a 1/0 column is the proportion of 1s."

In [ ]:
df['Risk_flag'].mean().round(3)

np.float64(0.224)

### ✅ Checkpoint 3: commit, e.g. *"Added new columns and encoded categories"*

## Step 8 · Ask the data  *(Task 1)*

**8.1** Rate by Gender

In [ ]:
df.groupby('Gender')['Risk_flag'].mean().round(3)

Gender
Female    0.230
Male      0.219
Name: Risk_flag, dtype: float64

**8.2** Rate by Physical_Activity

In [ ]:
df.groupby('Physical_Activity')['Risk_flag'].mean().round(3)

Physical_Activity
Active       0.126
Light        0.235
Moderate     0.160
Sedentary    0.314
Name: Risk_flag, dtype: float64

**8.3** Rate by Age_band

In [ ]:
df.groupby('Age_band')['Risk_flag'].mean().round(3)

Age_band
30-44       0.171
45-59       0.250
60+         0.369
Under 30    0.110
Name: Risk_flag, dtype: float64

**8.4** Another variable (your choice)

In [ ]:
df.groupby('Diet_Quality')['Risk_flag'].mean().round(3)

Diet_Quality
Average      0.232
Excellent    0.204
Good         0.219
Poor         0.227
Name: Risk_flag, dtype: float64

**8.5 The "too obvious" columns.** Ask what is going on:

In [ ]:
df.groupby('Diabetes_Risk')[['Fasting_Glucose_mg_dL', 'HbA1c_percent']].mean().round(2)

               Fasting_Glucose_mg_dL  HbA1c_percent
Diabetes_Risk
No                             86.33           4.06
Yes                           103.86           4.75

**8.6** Crosstab

In [ ]:
pd.crosstab(df['Risk_Category'], df['Diabetes_Risk'])

Diabetes_Risk    No   Yes
Risk_Category
Normal         6206  1781
Prediabetes       0    13

**Say:** "Glucose and HbA1c differ strongly between the groups because they measure the condition itself, not lifestyle causes. Treat them as outcome markers. Your blood pressure columns are stronger still: they define hypertension, so they cannot explain it." (The `Prediabetes` group here is only 13 patients, all Yes.)

## Step 9 · Reusable code: functions  *(2b)*
**Say:** "The brief asks for readable, organised, reusable code. Wrap the steps in functions, then run them in a few lines."

**9.1** `load_data`

In [ ]:
def load_data(path):
    return pd.read_csv(path)

**9.2** `clean_data`

In [ ]:
def clean_data(data):
    data = data.drop_duplicates().copy()
    data['Gender'] = data['Gender'].replace({'F': 'Female', 'female': 'Female', 'M': 'Male', 'male': 'Male'})
    data['Waist_Circumference_cm'] = data['Waist_Circumference_cm'].fillna(data['Waist_Circumference_cm'].median())
    data['Sleep_Hours'] = data['Sleep_Hours'].fillna(data['Sleep_Hours'].median())
    data['Screen_Time_Hours'] = data['Screen_Time_Hours'].fillna(data['Screen_Time_Hours'].median())
    data['Cholesterol_mg_dL'] = data['Cholesterol_mg_dL'].fillna(data['Cholesterol_mg_dL'].median())
    data['Insulin_Level'] = data['Insulin_Level'].fillna(data['Insulin_Level'].median())
    data['Diet_Quality'] = data['Diet_Quality'].fillna(data['Diet_Quality'].mode()[0])
    data['Stress_Level'] = data['Stress_Level'].fillna(data['Stress_Level'].mode()[0])
    data['Alcohol_Consumption'] = data['Alcohol_Consumption'].fillna('None')
    return data

**9.3** `add_features`

In [ ]:
def add_features(data):
    data = data.copy()
    data['BMI_group'] = data['BMI'].apply(bmi_group)
    data['Age_band'] = data['Age'].apply(age_band)
    data['Risk_flag'] = (data['Diabetes_Risk'] == 'Yes').astype(int)
    return data

**9.4** Chain them. **Say:** "Three functions, one line, from raw file to analysis-ready table."

In [ ]:
df2 = add_features(clean_data(load_data('diabetes_risk_teaching_dataset_8000.csv')))
print(df2.shape, df2.isnull().sum().sum())

(8000, 22) 0

**9.5** Save, then commit

In [ ]:
df.to_csv('diabetes_clean.csv', index=False)

## Step 10 · Advanced Tasks

**A1** Function for groups

In [ ]:
def rate_by_group(data, column):
    return data.groupby(column)['Risk_flag'].mean().round(3)

**A1b / A1c** Call it

In [ ]:
rate_by_group(df, 'Diet_Quality')

Diet_Quality
Average      0.232
Excellent    0.204
Good         0.219
Poor         0.227
Name: Risk_flag, dtype: float64

In [ ]:
rate_by_group(df, 'Smoking_Status')

Smoking_Status
Current    0.231
Former     0.218
Never      0.225
Name: Risk_flag, dtype: float64

**A2** Two variables at once

In [ ]:
pd.pivot_table(df, values='Risk_flag', index='Physical_Activity', columns='Smoking_Status', aggfunc='mean').round(3)

Smoking_Status     Current  Former  Never
Physical_Activity
Active               0.119   0.138  0.123
Light                0.250   0.227  0.234
Moderate             0.158   0.150  0.166
Sedentary            0.332   0.306  0.312

**A3** Correlations

In [ ]:
df.select_dtypes(include='number').corr()['Fasting_Glucose_mg_dL'].sort_values(ascending=False).round(2)

Fasting_Glucose_mg_dL           1.00
HbA1c_percent                   0.69
Risk_flag                       0.57
BMI                             0.57
Waist_Circumference_cm          0.52
Age                             0.29
Insulin_Level                   0.20
Blood_Pressure_Systolic_mmHg    0.12
Lifestyle_risk_count            0.12
Cholesterol_mg_dL               0.11
Sleep_Hours                     0.02
Family_History_flag             0.00
Diet_Quality_code              -0.00
Screen_Time_Hours              -0.00
Stress_Level_code              -0.02
Waist_per_BMI                  -0.23
Physical_Activity_code         -0.32
Name: Fasting_Glucose_mg_dL, dtype: float64

**A4** Missing-data pattern (is anything missing more for the young?)

In [ ]:
raw = load_data('diabetes_risk_teaching_dataset_8000.csv')
raw[['Cholesterol_mg_dL', 'Insulin_Level', 'Waist_Circumference_cm']].isnull().groupby(raw['Age'] < 35).mean().round(3)

       Cholesterol_mg_dL  Insulin_Level  Waist_Circumference_cm
Age
False              0.032          0.040                   0.021
True               0.032          0.042                   0.025